// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { ConfigService } from '@nestjs/config';
import 'dotenv/config';
import { defineConfig } from 'prisma/config';
import { EnvironmentVariables } from './src/config/env.validation.js';

const configService = new ConfigService<EnvironmentVariables>();

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: configService.getOrThrow('DATABASE_URL'),
  },
});
