// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { ConfigService } from '@nestjs/config';
import dotenv from 'dotenv';
import { existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { defineConfig } from 'prisma/config';
import { EnvironmentVariables } from './src/config/env.validation.js';

const rootEnvPath = resolve(import.meta.dirname, '../.env');
const backendEnvPath = resolve(import.meta.dirname, '.env');

dotenv.config({
  path: existsSync(rootEnvPath) ? rootEnvPath : backendEnvPath,
});

const configService = new ConfigService<EnvironmentVariables>();

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: configService.getOrThrow('DATABASE_URL'),
  },
});
